# -*- coding: utf-8 -*-
"""minor project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rzSkY2P2HQjx8Mi86RT-ScPjR-xSdUrL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# RobustScaler is imported but not used in this data preparation block, keeping for consistency if needed later.
from sklearn.preprocessing import RobustScaler
from google.colab import files
import os

# Standard visualization setup
sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (10,6)

# --- Consolidated Data Loading, Cleaning, and Feature Engineering ---

try:
    # Attempting to load the local file from /content/
    df = pd.read_csv("/content/credit_card_cleaned.csv")
    print("Data loaded from /content/credit_card_cleaned.csv successfully.")

except FileNotFoundError:
    print("Error: 'credit_card_cleaned.csv' not found in /content/. Please upload the file.")
    print("Attempting to prompt for upload...")
    uploaded = files.upload()
    for filename in uploaded.keys():
        # Move the uploaded file to /content/ if it was uploaded elsewhere
        if not os.path.exists(os.path.join('/content/', filename)):
            os.rename(filename, os.path.join('/content/', filename))
        print(f"File {filename} uploaded successfully to /content/")
    try:
        df = pd.read_csv("/content/credit_card_cleaned.csv")
        print("Data loaded after user upload.")
    except Exception as e_upload:
        print(f"Failed to load data even after upload: {e_upload}")
        df = pd.DataFrame() # Initialize empty DataFrame to prevent NameError later

if not df.empty:
    # Cleaning and Preprocessing
    df = df.drop_duplicates()
    if 'ID' in df.columns:
        df.drop('ID', axis=1, inplace=True)

    # Handle Missing Values (based on 7NjMr_xM9AWZ, though previous output showed none)
    for col in df.select_dtypes(include=np.number).columns:
        df[col] = df[col].fillna(df[col].median())

    # Correct invalid categorical values
    df['EDUCATION'] = df['EDUCATION'].replace([0,5,6],4)
    df['MARRIAGE'] = df['MARRIAGE'].replace(0,3)

    # Feature Engineering (Combined from original c481cf99 and R3ldcb469Krt)
    df['TOTAL_BILL'] = df[['BILL_AMT1','BILL_AMT2','BILL_AMT3','BILL_AMT4','BILL_AMT5','BILL_AMT6']].sum(axis=1)
    df['TOTAL_PAYMENT'] = df[['PAY_AMT1','PAY_AMT2','PAY_AMT3','PAY_AMT4','PAY_AMT5','PAY_AMT6']].sum(axis=1)

    # Credit Utilization Ratio (Using R3ldcb469Krt's definition: no +1)
    df['CREDIT_UTILIZATION'] = df['TOTAL_BILL'] / df['LIMIT_BAL']

    df['PAYMENT_DELAY_SCORE'] = df[['PAY_1','PAY_2','PAY_3','PAY_4','PAY_5','PAY_6']].sum(axis=1)

    # Risk Score (New from R3ldcb469Krt)
    df['RISK_SCORE'] = df['PAYMENT_DELAY_SCORE'] + df['CREDIT_UTILIZATION']

    # Risk Category (Using R3ldcb469Krt's definition)
    def risk_category(score):
        if score <= 0: return 'Low Risk'
        elif score <= 4: return 'Medium Risk'
        else: return 'High Risk'

    df['RISK_LEVEL'] = df['PAYMENT_DELAY_SCORE'].apply(risk_category)

    # Final categorical conversion
    for col in ['SEX','EDUCATION','MARRIAGE','DEFAULT']:
        if col in df.columns:
            df[col] = df[col].astype('category')

    print("Data loaded, cleaned, and 'df' with all features initialized successfully.")
else:
    print("DataFrame 'df' is empty after loading attempts. Please ensure the CSV file is correctly uploaded.")

from google.colab import files
import os

print("Please upload 'credit_card_cleaned.csv':")
uploaded = files.upload()

# Move the file to /content/ if it was uploaded elsewhere
for filename in uploaded.keys():
    os.rename(filename, os.path.join('/content/', filename))
    print(f"File {filename} uploaded successfully to /content/")

# Loading of dataset
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (10,6)

# ==========================================================
# 1 DATA LOADING
# ==========================================================
from google.colab import files

uploaded = files.upload()
df = pd.read_csv("/content/credit_card_cleaned.csv")

print("Dataset Shape:", df.shape)
print(df.head())

# Data Cleaning
df = df.drop_duplicates()

# Check missing values
print("\nMissing Values")
print(df.isnull().sum())

# Fill missing values using median
for col in df.select_dtypes(include=np.number).columns:
    df[col] = df[col].fillna(df[col].median())

# Rename column for easier use
df.rename(columns={'default payment next month':'DEFAULT'}, inplace=True)

# Drop ID column if present
if 'ID' in df.columns:
    df.drop('ID', axis=1, inplace=True)

# Correct invalid categorical values
df['EDUCATION'] = df['EDUCATION'].replace([0,5,6],4)
df['MARRIAGE'] = df['MARRIAGE'].replace(0,3)

# Convert categorical columns
categorical_columns = ['SEX','EDUCATION','MARRIAGE','DEFAULT']

for col in categorical_columns:
    df[col] = df[col].astype("category")

print("\nDataset After Cleaning:", df.shape)

df['TOTAL_BILL'] = (
    df['BILL_AMT1'] + df['BILL_AMT2'] + df['BILL_AMT3'] +
    df['BILL_AMT4'] + df['BILL_AMT5'] + df['BILL_AMT6']
)

# Total Payment Amount
df['TOTAL_PAYMENT'] = (
    df['PAY_AMT1'] + df['PAY_AMT2'] + df['PAY_AMT3'] +
    df['PAY_AMT4'] + df['PAY_AMT5'] + df['PAY_AMT6']
)

# Credit Utilization Ratio
df['CREDIT_UTILIZATION'] = df['TOTAL_BILL'] / df['LIMIT_BAL']

# Payment Delay Score
df['PAYMENT_DELAY_SCORE'] = (
    df['PAY_1'] + df['PAY_2'] + df['PAY_3'] +
    df['PAY_4'] + df['PAY_5'] + df['PAY_6']
)

# Risk Score
df['RISK_SCORE'] = df['PAYMENT_DELAY_SCORE'] + df['CREDIT_UTILIZATION']

# Risk Category
def risk_category(score):
    if score <= 0:
        return "Low Risk"
    elif score <= 4:
        return "Medium Risk"
    else:
        return "High Risk"

df['RISK_LEVEL'] = df['PAYMENT_DELAY_SCORE'].apply(risk_category)

print(df[['RISK_SCORE','RISK_LEVEL']].head())

# ==========================================================
# 4 BASIC STATISTICS
# ==========================================================

print(df.describe())

# =========================================

# FINAL HIGH-ACCURACY PIPELINE (FIXED)

# =========================================

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import accuracy_score, roc_auc_score, f1_score, precision_score, recall_score
from sklearn.ensemble import RandomForestClassifier, VotingClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

# =========================================

# PREPROCESS (SAFE)

# =========================================

X = df.drop(['DEFAULT','RISK_LEVEL','RISK_SCORE','PAYMENT_DELAY_SCORE'], axis=1, errors='ignore')
y = df['DEFAULT']

X = pd.get_dummies(X, drop_first=True)
X = X.replace([np.inf, -np.inf], 0)
X = X.fillna(X.median())

# =========================================

# SPLIT

# =========================================

X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.25, random_state=30, stratify=y
)

# =========================================

# SMOTE

# =========================================

smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

# =========================================

# MODELS

# =========================================

rf = RandomForestClassifier(
n_estimators=400,
max_depth=20,
class_weight='balanced_subsample',
n_jobs=-1,
random_state=42
)

xgb = XGBClassifier(
n_estimators=500,
max_depth=6,
learning_rate=0.05,
subsample=0.9,
colsample_bytree=0.9,
eval_metric='logloss',
n_jobs=-1,
random_state=42
)

lgbm = LGBMClassifier(
n_estimators=500,
max_depth=8,
learning_rate=0.05,
num_leaves=63,
class_weight='balanced',
n_jobs=-1,
random_state=42,
verbose=-1
)

# =========================================

# STACKING (BEST MODEL)

# =========================================

stacking_model = StackingClassifier(
estimators=[
('rf', rf),
('xgb', xgb),
('lgbm', lgbm)
],
final_estimator=LogisticRegression(max_iter=1000),
cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42),
stack_method='predict_proba',
n_jobs=-1
)

print("Training stacking model...")
stacking_model.fit(X_train_res, y_train_res)

# =========================================

# PREDICTIONS (PROBABILITY)

# =========================================

y_prob = stacking_model.predict_proba(X_test)[:, 1]

# =========================================

# THRESHOLD TUNING (KEY FOR ACCURACY)

# =========================================

best_acc = 0
best_thresh = 0.5

for t in np.arange(0.3, 0.7, 0.01):
    preds = (y_prob >= t).astype(int)
    acc = accuracy_score(y_test, preds)
    if acc > best_acc:
        best_acc = acc
        best_thresh = t

y_pred = (y_prob >= best_thresh).astype(int)

# =========================================

# RESULTS

# =========================================

print("\nBest Threshold:", best_thresh)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC AUC:", roc_auc_score(y_test, y_prob))
print("F1 Score:", f1_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataframe and handle the analysis
try:
    df = pd.read_csv('/content/credit_card_cleaned.csv')

    # Exclude non-numeric columns and target/prediction columns
    numeric_cols = df.select_dtypes(include=['int64','float64']).columns.drop(['RF_PREDICTION', 'DEFAULT'], errors='ignore')

    # Dynamically calculate subplot grid size
    num_plots = len(numeric_cols)
    n_cols = 5
    n_rows = (num_plots + n_cols - 1) // n_cols

    plt.figure(figsize=(n_cols * 4, n_rows * 3))

    for i, col in enumerate(numeric_cols):
        plt.subplot(n_rows, n_cols, i+1)
        sns.histplot(df[col], kde=True)
        plt.title(col)
        plt.xlabel("")
        plt.ylabel("Density")

    plt.tight_layout()
    plt.show()

    skew_values = df[numeric_cols].skew()
    print("Skewness of each feature:\n")
    print(skew_values.sort_values(ascending=False))

    plt.figure(figsize=(12,6))
    skew_values.sort_values().plot(kind="barh")
    plt.title("Skewness of Numerical Features")
    plt.xlabel("Skewness")
    plt.show()
except FileNotFoundError:
    print("Error: 'credit_card_cleaned.csv' not found. Please upload the file first.")
except Exception as e:
    print(f"An error occurred: {e}")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import RobustScaler
from google.colab import files
import os

# Standard visualization setup
sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (10,6)

# --- Consolidated Data Loading, Cleaning, and Feature Engineering ---
# This block is copied from c481cf99 to ensure df is always available and fully processed.
try:
    # Attempting to load the local file from /content/
    df = pd.read_csv("/content/credit_card_cleaned.csv")
    print("Data loaded from /content/credit_card_cleaned.csv successfully.")

except FileNotFoundError:
    print("Error: 'credit_card_cleaned.csv' not found in /content/. Please upload the file.")
    print("Attempting to prompt for upload...")
    uploaded = files.upload()
    for filename in uploaded.keys():
        # Move the uploaded file to /content/ if it was uploaded elsewhere
        if not os.path.exists(os.path.join('/content/', filename)):
            os.rename(filename, os.path.join('/content/', filename))
        print(f"File {filename} uploaded successfully to /content/")
    try:
        df = pd.read_csv("/content/credit_card_cleaned.csv")
        print("Data loaded after user upload.")
    except Exception as e_upload:
        print(f"Failed to load data even after upload: {e_upload}")
        df = pd.DataFrame() # Initialize empty DataFrame to prevent NameError later

if not df.empty:
    # Cleaning and Preprocessing
    df = df.drop_duplicates()
    if 'ID' in df.columns:
        df.drop('ID', axis=1, inplace=True)

    # Handle Missing Values (based on 7NjMr_xM9AWZ, though previous output showed none)
    for col in df.select_dtypes(include=np.number).columns:
        df[col] = df[col].fillna(df[col].median())

    # Correct invalid categorical values
    df['EDUCATION'] = df['EDUCATION'].replace([0,5,6],4)
    df['MARRIAGE'] = df['MARRIAGE'].replace(0,3)

    # Feature Engineering (Combined from original c481cf99 and R3ldcb469Krt)
    df['TOTAL_BILL'] = df[['BILL_AMT1','BILL_AMT2','BILL_AMT3','BILL_AMT4','BILL_AMT5','BILL_AMT6']].sum(axis=1)
    df['TOTAL_PAYMENT'] = df[['PAY_AMT1','PAY_AMT2','PAY_AMT3','PAY_AMT4','PAY_AMT5','PAY_AMT6']].sum(axis=1)

    # Credit Utilization Ratio (Using R3ldcb469Krt's definition: no +1)
    df['CREDIT_UTILIZATION'] = df['TOTAL_BILL'] / df['LIMIT_BAL']

    df['PAYMENT_DELAY_SCORE'] = df[['PAY_1','PAY_2','PAY_3','PAY_4','PAY_5','PAY_6']].sum(axis=1)

    # Risk Score (New from R3ldcb469Krt)
    df['RISK_SCORE'] = df['PAYMENT_DELAY_SCORE'] + df['CREDIT_UTILIZATION']

    # Risk Category (Using R3ldcb469Krt's definition)
    def risk_category(score):
        if score <= 0: return 'Low Risk'
        elif score <= 4: return 'Medium Risk'
        else: return 'High Risk'

    df['RISK_LEVEL'] = df['PAYMENT_DELAY_SCORE'].apply(risk_category)

    # Final categorical conversion
    for col in ['SEX','EDUCATION','MARRIAGE','DEFAULT']:
        if col in df.columns:
            df[col] = df[col].astype('category')

    print("DataFrame 'df' with all features initialized successfully for plotting.")

    # Original plotting code from CioHxG8B9gVR
    # Correlation Heatmap
    plt.figure(figsize=(12,10))
    numeric_df = df.select_dtypes(include=np.number)
    corr = numeric_df.corr()
    sns.heatmap(corr, cmap='coolwarm', annot=False)
    plt.title("Correlation Heatmap")
    plt.show()

    # Bar Graph
    default_counts = df['DEFAULT'].value_counts()
    plt.bar(['No Default','Default'], default_counts)
    plt.title("Default Payment Distribution")
    plt.xlabel("Default Status")
    plt.ylabel("Number of Customers")
    plt.show()

    # Risk Level Distribution
    sns.countplot(x='RISK_LEVEL', data=df)
    plt.title("Customer Risk Level Distribution")
    plt.show()
else:
    print("DataFrame 'df' is empty after loading attempts. Plotting skipped.")

# Histogram
df.hist(bins=30, figsize=(14,10))
plt.suptitle("Histogram Distribution of Features")
plt.show()

plt.figure(figsize=(12,6))
sns.boxplot(data=df[['LIMIT_BAL','AGE','TOTAL_BILL','TOTAL_PAYMENT']])
plt.title("Box Plot for Financial Features")
plt.show()

# violin plot
plt.figure(figsize=(10,6))
sns.violinplot(x='DEFAULT', y='LIMIT_BAL', data=df)
plt.title("Violin Plot: Credit Limit vs Default Risk")
plt.show()

# Risk monitoring output
print("\nRisk Level Summary")
print(df['RISK_LEVEL'].value_counts())

# Average credit utilization per risk group

risk_summary = df.groupby('RISK_LEVEL')['CREDIT_UTILIZATION'].mean()

print("\nAverage Credit Utilization by Risk Level")
print(risk_summary)

# Matrix plot
sns.pairplot(
    df[['LIMIT_BAL','AGE','TOTAL_BILL','TOTAL_PAYMENT','DEFAULT']],
    hue='DEFAULT'
)

plt.show()